# Информация о сайте
site_name: Privacy Russia
site_url: https://privacy-russia.github.io
copyright: Copyright &copy; 2024 Privacy Russia

# Репозиторий гитхаб
repo_name: Github
repo_url: https://github.com/privacy-russia/privacy-russia.github.io

# Конфигурация
theme: 
  logo: assets/icons/site-icons/privacy-russia.svg
  favicon: assets/icons/site-icons/privacy-russia.svg
  language: ru
  name: material
  font:
    text: Roboto
  custom_dir: overrides

  palette: 
    # Palette toggle for light mode
    - scheme: default
      accent: light-blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Включить тёмную тему

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Отключить тёмную тему

  features:
    - navigation.sections
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
    - content.tabs.link
  icon:
    repo: fontawesome/brands/github
    annotation: material/chevron-right-circle

plugins:
  - search
  - git-revision-date-localized:
      locale: ru
      enable_creation_date: false

extra:
  generator: false
  social: 
    - icon: fontawesome/brands/telegram
      link: https://t.me/privacy_russia
      name: Наш телеграм

markdown_extensions:
  - toc:
     # slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}
      permalink: false 
      permalink_title: hello
  - attr_list   # Поддержка картинок
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - md_in_html  # Поддержка картинок
  - abbr
  - admonition  
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_css:
  - stylesheets/extra.css

# Структура сайта
nav:
  - Главная: index.md
  - Рекомендации: 
    - rekomendacii-programm/index.md
    - Программы:
      - Менеджер паролей: rekomendacii-programm/menedzhery-paroley.md
      - 2ФА: rekomendacii-programm/mfa.md  
      - Мессенджеры: rekomendacii-programm/mesendzhery.md
      - Браузер: rekomendacii-programm/desktopnye-brauzery.md

  - База знаний: 
    - baza-znaniy/index.md
    - baza-znaniy/mfa.md
    - baza-znaniy/elektronnaya-pochta.md